Dependency injection: Presenters.
peckadesign/BestPractices pull request #2
Opened 2017-07-05 07:34 UTC by klobinoid

DI v presentrech. Něco doplnit / změnit?

2017-07-05 09:32 UTC, MilanPala approved these changes
Podle mě tam jsou všechny případy.

2017-07-05 09:32 UTC, MilanPala commented on DependencyInjection/App/Presenters/AnotherPresenter.php
> +	 * @var \Vendor\Services\AnotherVendorService
Pokud mám být striktní, tak je naimportovaný vendor NS, takže ne FQN. Myslím, že v CS je to taky takto uvedeno.

2017-07-05 09:32 UTC, MilanPala commented on DependencyInjection/App/Presenters/AnotherPresenter.php
> +	/**
Jednou jsme řešili víceřadkové dokumentační komentáře. Jsou potřeba jen u metod, nikde jinde nedávají význam. To si bude pamatovat @vitkutny. Nevznikl z toho nějaký závěr?

2017-07-05 09:33 UTC, MilanPala requested changes
Chybí ti Makefile, který je napojený na CS. Ostatní cíle mohou být prázdné.

2017-07-10 06:59 UTC, klobinoid commented on DependencyInjection/App/Presenters/AnotherPresenter.php
> +	/**
pokud ano, tak o něm nevím. @vitkutny sám používá víceřádkové anotace i v inline kódu, což je za mě zufíl...

evidentně je kolem toho spíš zmatek, viz https://github.com/peckadesign/pdproject5/pull/1129#discussion_r126338322, takže bychom to měli sjednotit

2017-07-10 07:01 UTC, klobinoid commented on DependencyInjection/App/Presenters/AnotherPresenter.php
> +	 * @var \Vendor\Services\AnotherVendorService
klidně, ale takto to generuje phpstorm i ve chvíli, kdy už NS naimportovány - máš to nějak nastavený nebo to otrocky umazáváš?

2017-07-10 07:13 UTC, jankaderabek commented on DependencyInjection/App/Presenters/AnotherPresenter.php
> +	 * @var \Vendor\Services\AnotherVendorService
![image](https://user-images.githubusercontent.com/7320529/28006526-f14adae6-654f-11e7-8779-0bae578e99f0.png)

2017-07-10 07:15 UTC, klobinoid commented on DependencyInjection/App/Presenters/AnotherPresenter.php
> +	 * @var \Vendor\Services\AnotherVendorService
@jankaderabek 👍 díky

2017-07-10 07:35 UTC, MilanPala commented on DependencyInjection/App/Presenters/AnotherPresenter.php
> +	 * @var \Vendor\Services\AnotherVendorService
Očividně nastavené, protože mi to nedělá. Zřejmě volba `Editor`, `Intentions`, `PHP` a `Import class`. Případně dej najít nastavení `fully`. Jinak nevím, kde by se to mohlo měnit

2017-07-10 07:35 UTC, MilanPala commented on DependencyInjection/App/Presenters/AnotherPresenter.php
> +	 * @var \Vendor\Services\AnotherVendorService
![preferences 2017-07-10 09-35-36](https://user-images.githubusercontent.com/1717814/28007290-2559a63e-6553-11e7-98ea-030fba14acf3.png)

2017-07-10 08:34 UTC, klobinoid commented
Doplněn Makefile, fixnuto názvosloví + FQN v docblocích

2017-07-11 12:32 UTC, klobinoid commented
fixnul jsem CS v declare statementu, squashnuto a rebasnuto. @MilanPala mrkni na to pls a mergnuli bychom to

2017-07-11 14:46 UTC, MilanPala approved these changes

2017-07-11 14:47 UTC, merged